api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
from rest_framework.authtoken import views as authtoken_views
from api import views


schema_view = get_schema_view(title="Pastebin Api")


router = DefaultRouter()

urlpatterns = [
    path('api-token-auth/', authtoken_views.obtain_auth_token, name="obtain-token"),
    path("schema/", schema_view, name="schema"),
    path("boats/<int:pk>/", views.BoatDetailView.as_view(), name="boatmodel-detail"),
    path("boats/", views.BoatsListView.as_view(), name="boatmodel-list"),
    path("users/login/", views.UserLoginView.as_view(), name="login"),
    path("users/registration/", views.UserRegistrationView.as_view(), name="user-registration"),
    path("users/profile/", views.UserProfileView.as_view(), name="user-profile"),
    path("users/<int:pk>/", views.ExtraUserDetailView.as_view(), name="extrauser-detail"),
    path("users", views.ExtraUserListView.as_view(), name="extrauser-list"),
    path("product/search/", views.ProductSearchListView.as_view(), name="product-search"),
    path("product/suggest/<str:word>/", views.SuggestionView.as_view(), name="product-suggest"),
    path("", views.api_root, name="api-root"),

]

articles/urls.py
from django.urls import path
from .views import *

app_name = 'articles'
urlpatterns = [
    path("<int:current_heading_pk>/<int:pk>/", ContentListView.as_view(), name="detail"),
    path("<int:pk>/", show_by_heading_view, name="show_by_heading"),
    path("comment/edit/<int:pk>/", EditCommentsView.as_view(), name="edit_comment"),
    path("comment/<str:key>/<int:pk>/", DoubleCommentView.as_view(), name="comment"),
    path("article_delete/<int:pk>/", ArticleDeleteView.as_view(), name="article_delete"),
    path("article_edit/<int:pk>/", ArticleEditView.as_view(), name="article_edit"),
    path("add_article/<int:pk>/", AddArticleView.as_view(), name="add_article"),
    path("add_heading/<int:pk>/", headingcreateview, name="add_heading"),
    path("resurrection/", ArticleResurrectionView.as_view(), name="resurrection"),
    path("", ArticlesMainView.as_view(), name="articles_main"),

]

boats/urls.py
from django.urls import path
from .views import *

app_name = 'boats'
urlpatterns = [

    path("accounts/reset/<uidb64>/<token>/", PassResConfView.as_view(), name='password_reset_confirm'),
    path("accounts/password_reset/", PassResView.as_view(), name="password_reset"),
    path("accounts/register/activate/<str:sign>/", user_activate_view, name="register_activate"),
    path('account/password/change', PasswordCorrectionView.as_view(), name="password_change"),
    path("account/profile/registerdone/", RegisterDoneView.as_view(), name="register_is_done"),
    path("accounts/profile/delete/", DeleteUserView.as_view(), name="profile_delete"),
    path("accounts/profile/change/", CorrectUserInfoView.as_view(), name="profile_change"),
    path("accounts/profile/add/", AddNewUserView.as_view(), name="add_new_user"),
    path("accounts/logout/", AdminLogoutView.as_view(), name="logout"),
    path("accounts/profile/", UserProfileView.as_view(), name='user_profile'),
    path("accounts/login/", AdminLoginView.as_view(), name="login"),
    path("boats/edit/<int:pk>/", viewname_edit, name="boat_edit"),
    path("boats/detail/<int:pk>/", boat_detail_view, name="boat_detail"),
    path("boats/delete/<int:pk>/", BoatDeleteView.as_view(), name="boat_delete"),
    path("boats/create/", viewname, name="boat_create"),
    path("boats/reversion/delete/<int:pk>/", ReversionDeleteView.as_view(),
         name="reversion_delete"),
    path("boats/reversion/confirmation/<int:pk>/", reversion_confirm_view,
         name="reversion_confirmation"),
    path("boats/reversion/", ReversionView.as_view(), name="reversion"),
    path("boats/render/pdf_to_file/<int:pk>/", render_pdf_view, name="pdf_to_file"),
    path("boats/render/pdf/<int:pk>/", Pdf.as_view(), name="pdf"),
    path("boats/rollback/<int:pk>/<int:version_id>/", RollbackView.as_view(), name="rollback"),
    path("boats/blocket/<int:pk>/<str:name>/", BlocketView.as_view(), name="blocket"),
    path("boats/", BoatListView.as_view(), name="boats"),
    path("feedback/", feedback_view, name="feedback"),
    path("map/<int:pk>/", map_show, name="map"),
    path("", IndexPageView.as_view(), name="index"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib. staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.views.defaults import permission_denied, page_not_found, server_error
from django.utils.functional import curry
from django.conf import settings
from django.conf.urls import url


urlpatterns = [
    path("social/", include('social_django.urls', namespace='social')),
    path("captcha/", include("captcha.urls")),
    path('admin/', admin.site.urls),
    path("articles/", include("articles.urls")),
    path("", include("boats.urls")),
    url(r'fancy-cache', include('fancy_cache.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path("api/", include("api.urls")),
]

# для отдачи статики в дебаг = фалс ---manage.py runserver --insecure
if settings.DEBUG:
    urlpatterns.append(path("static/<path:path>", never_cache(serve)))  # если не загр. картинки то смотреть сюда
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

# обработчик 403 ошибки(Access denied)
handler403 = curry(permission_denied, exception=Exception('Permission Denied'),
                   template_name='errors/403.html')
# обработчик 404 ошибки(Not Found)
handler404 = curry(page_not_found, exception=Exception('Page not Found'),
                   template_name='errors/404.html')

# названия для админки
admin.site.site_header = "Boat's project  Admin"
admin.site.site_title = "BOATS Admin Portal"
admin.site.index_title = "BOATS administration page"

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.core.paginator import Paginator
from django.db.models import Q
from fancy_cache import cache_page
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView, FormView
from django.views.decorators.vary import vary_on_cookie, vary_on_headers
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Article, Comment, Heading, SubHeading, UpperHeading
from .forms import *
import unidecode
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, Http404
from django.db.transaction import atomic
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from boats.decorators import login_required_message, MessageLoginRequiredMixin
from django.utils.decorators import method_decorator
from django.core.cache import cache
import datetime


def vary_on_user_is_authenticated(request):
    """Функция для key_prefix"""
    return request.user.is_authenticated

"""контроллер гл. стр. артиклес"""


def vary_on_ArticlesMainView(request):
    upperhaeding_last_change = UpperHeading.objects.all().values_list('change_date',
                                                                flat=True).latest("change_date")
    subheading_last_change = SubHeading.objects.all().values_list('change_date', flat=True).latest(
        "change_date")
    timedelta1 = (datetime.datetime.now() - upperhaeding_last_change).seconds > 1
    timedelta2 = (datetime.datetime.now() - subheading_last_change).seconds > 1
    mark2 = cache.get("mark2")  # forms 187 str
    return "ArticlesMainView+%s+%s+%s+%s" % (mark2, timedelta1, timedelta2,
                                             request.user.is_authenticated)


#  инвалидация в сигналах по урлу и в модели лодки в методе делит и по key_prefix
@method_decorator(cache_page(60*60*24, key_prefix=vary_on_ArticlesMainView), name='dispatch')
class ArticlesMainView(TemplateView):
    template_name = "articles/articles_index.html"


""" контроллер показывающий статьи по под-рубрикам + поиск + пагинатор """


def vary_on_paginated_or_not(request):
    pk = request.get_full_path_info().split("/")[-2]
    # Смотрим есть ли на странице пагинация или нет по кол-ву выводимых объектов
    count_eq = Article.objects.filter(foreignkey_to_subheading=int(pk)).count()
    # время удаления последней статьи
    try:
        change_date_of_deleted_article = Article.default.filter(foreignkey_to_subheading=int(
            pk), show=False).values_list("change_date", flat=True).latest("change_date")
        timedelta = (datetime.datetime.now() - change_date_of_deleted_article).seconds > 1
    except (ObjectDoesNotExist, TypeError):
        timedelta = True
    return "show_by_heading_view+%s+%s+%s+%s" % (True if count_eq > 10 else False,
                                           request.user.is_authenticated, timedelta, count_eq)


#  инвалидация в сигналах по урлу и по key_prefix и в формах ArticleResurrectionForm
@cache_page(60*60*24*7, key_prefix=vary_on_paginated_or_not)
def show_by_heading_view(request, pk): #597
    current_heading = get_object_or_404(SubHeading, pk=pk)
    list_of_articles = Article.objects.filter(foreignkey_to_subheading=pk)
    if "keyword" in request.GET:
        keyword = request.GET["keyword"]
        keyword_unidecode = unidecode.unidecode(keyword)
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword) | Q(
            title__icontains=keyword_unidecode) | Q(content__icontains=keyword_unidecode)
        list_of_articles = list_of_articles.filter(q)
    else:
        keyword = ""
    form = SearchForm(initial={"keyword": keyword})
    paginator = Paginator(list_of_articles, 10)
    if "page" in request.GET:
        page_num = request.GET["page"]
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {"current_heading": current_heading, "page": page,
               "list_of_articles": page.object_list, "form": form}  # 597
    return render(request, "articles/show_by_subheading.html", context)


""" контроллер просмотра конкретной статьи"""


def contentlistview_key_prefix(request):
    pk = int(request.get_full_path_info().split("/")[-2])
    #  время последнего изменения статьи
    last_change = Article.objects.filter(pk=pk).values("change_date")[0].get("change_date")
    #  разница текущего времени и времени последнего изменения статьи. Нужна для того, чтобы
    #  различать ситуации когда нужно или не нужно выводить сообщения. Т.е имеем 2 версии кеша
    #  1) с сообщением 2) без сообщения
    timedelta = (datetime.datetime.now() - last_change).seconds > 1 if last_change else True
    try:
        last_change_comments = Comment.objects.filter(foreignkey_to_article_id=pk).values_list(
                                                "change_date", flat=True).latest("change_date")
        timedelta2 = (datetime.datetime.now() - last_change_comments).seconds > 1
    except ObjectDoesNotExist:
        timedelta2 = True
    return "ContentListView+%s+%s+%s" % (vary_on_user_is_authenticated(request), timedelta,
                                         timedelta2)


#  инвалидация по урлу в сигналах
@method_decorator(cache_page(60*60*24*7, key_prefix=contentlistview_key_prefix), name="dispatch")
class ContentListView(DetailView):
    template_name = "articles/content.html"
    model = Article

    def get_context_data(self, **kwargs):
        context = DetailView.get_context_data(self, **kwargs)
        if self.request.user.is_authenticated:
            context['user'] = ExtraUser.objects.get(pk=self.request.user.pk)
        context["comments"] = Comment.objects.filter(foreignkey_to_article_id=self.kwargs[
            "pk"])
        context["allowed_comments"] = \
           (self.request.get_signed_cookie('allowed_comments', default=None))
        return context


"""контроллер добавления новой статьи"""


#  без кеширования
class AddArticleView(SuccessMessageMixin, MessageLoginRequiredMixin, CreateView):
    model = Article
    template_name = "articles/create_article.html"
    form_class = ArticleForm
    success_message = "Article '%(title)s' has been successfully saved"
    redirect_message = "You must be authenticated in order to create new article"

    def get_initial(self):
        self.initial = CreateView.get_initial(self)
        self.initial["author"] = self.request.user
        if self.kwargs["pk"] and self.kwargs["pk"] != 0:
            self.initial["foreignkey_to_subheading"] =\
                get_object_or_404(SubHeading, pk=self.kwargs["pk"])
        try:  # устанавливаем нач. знач поля foreignkey_to_boat если заходим с категории                    #Articles on boats
            current_subheading = get_object_or_404(SubHeading, pk=self.kwargs["pk"])
            self.initial["foreignkey_to_boat"] = current_subheading.one_to_one_to_boat
        except Http404:
            pass
        return self.initial.copy()

    def get_success_url(self):
        """ передача через гет параметры кода того, была ли создана статьия из boats:detail.
         Нужно для корректной работы кнопки Back to Heading Или back to boat в зависимости
         откуда была создана статья"""
        path = self.request.POST.get("button", None)
        #  'http://127.0.0.1:8000/articles/add_article/329/'   пример
        if path and path.split("/")[3] == "boats":
            code = "boats"
        else:
            code = "articles"
        return "%s?code=%s" % (reverse('articles:detail',
                    args=(self.object.foreignkey_to_subheading_id, self.object.pk,)), code)


""" контроллер редактирования статьи"""


#  без кеширования
class ArticleEditView(SuccessMessageMixin, MessageLoginRequiredMixin, UpdateView):
    model = Article
    template_name = "articles/article_edit.html"
    form_class = ArticleForm
    success_message = "Article %(title)s has been edited and saved successfully "
    redirect_message = "You must be authenticated in order to edit this article"

    def get_success_url(self):
        return reverse('articles:detail',
                       args=(self.object.foreignkey_to_subheading.pk, self.object.pk, ))

    def get(self, request, *args, **kwargs):
        if self.get_object().author == self.request.user:
            return UpdateView.get(self, request, *args, **kwargs)
        else:
            messages.add_message(request, messages.WARNING,
                                 "You can only edit your own entries!",
                                 fail_silently=True)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


""" контроллер удаления  статьи"""


#  кеширование в шаблоне
class ArticleDeleteView(MessageLoginRequiredMixin, DeleteView):
    model = Article
    template_name = "articles/article_delete.html"
    redirect_message = "You must be authenticated in order to delete this article"

    def get_success_url(self):
        return reverse('articles:show_by_heading',
                       args=(self.object.foreignkey_to_subheading.pk, ))

    def get(self, request, *args, **kwargs):
        if self.get_object().author == self.request.user:
            return DeleteView.get(self, request, *args, **kwargs)
        else:
            message = 'Dear %s, you can only delete your own articles. This article has been' \
                      ' created by %s' % (self.request.user, self.get_object().author)
            messages.add_message(request, messages.WARNING, message=message, fail_silently=True,)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    def post(self, request, *args, **kwargs):

templates/articles/add_heading.html
<!-- templates/articles/add_heading.html  -->
{%  extends "base.html" %}
{%  load bootstrap4 %}
{% block title %}
    Add heading and/or subheading
{% endblock %}

{% block content %}
<script>
   $(document).ready(function() {
    $('.has-popover').popover({'trigger':'hover'});
});
</script>

    <div class="form-container container col-md-5   rounded   " style="margin-top: 10px; background-color: rgba(245,245,245,0.57); border: 2px ridge  rgba(253,253,253,0.57)">
    <div class="row bg-dark mb-2">
        <div class="col">
            <h4 class="text-center text-white no-gutters font-italic " >
                {% if  not form1.hidden_fields %}  ***New heading form*** {% else %} ***New sub-heading form*** {% endif %}</h4>
        </div>
    </div>

    <div class="row">
    <div class="col border-info  ">


    <form method="post" >
        {% csrf_token %}
        {%  if form1 %}
            {% bootstrap_form form1 %}
        {% endif %}
        {% bootstrap_form form2 %}


        <div class="row">
            <div class=" col text-center">
                {% buttons %}

                    <button type="submit"  name="submit"   class="form-button btn-lg btn-light rounded font-weight-bold text-muted">
                        Submit
                    </button>
                    <button type="reset" class="form-button btn-lg btn-light rounded font-weight-bold text-muted">
                        Reset
                    </button>
                {% endbuttons %}
            </div>
        </div>
    </form>
{% endblock content %}

templates/articles/articles_index.html
<!-- templates/articles/articles_index.html  -->
{%  extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{% bootstrap_jquery "full" %}

{% block title %}
    Articles main page
{% endblock %}
{% block content %}

    <style>
        .btn-group-vertical a, .btn-group-vertical button {
            width: 100%; margin-right: 20px;
        }
    </style>

<style>
        body {
            background-image: url({% static "articles/hobie-16-special-edition-16se.jpg" %});
            background-repeat: no-repeat, repeat;
            background-position: center, center;
            background-size: 33%;
            background-attachment: fixed;
        }
    </style>
{% comment %}
    <img class=" offset-6 " style="position: absolute;   " height=  width=  src="{% static "articles/hobie-16-special-edition-16se.jpg" %}" alt="training boat">
{% endcomment %}


    <div class="container-fluid mt-3 ">

        {%  for heading in subheadings %}
            <div class="row align-middle mb-2 align-self-start item">
                <div class = "col   ">

                    {%  ifchanged  heading.foreignkey.pk %}
                        <span class="nav-link root font-weight-bold align-middle">
        <span class="bg-info ml-0  rounded" style=" font-size: 20px">{{ heading.foreignkey.name }}</span>
        <a class="font-italic font-weight-light badge badge-dark ml-2" href="{%  url "articles:add_heading" pk=heading.foreignkey.pk %}">Add   Subheading</a>
        </span>{% endifchanged %}

                    <a class="ml-3"  style=" font-size: 18px" href="{% url "articles:show_by_heading" pk=heading.pk   %}">{{ heading.name|truncatechars:20 }} </a>

                    {% if not heading.cnt %}
                        <span class="badge badge-light text-muted"> EMPTY </span>

                    {% else %}
                        <span class="badge badge-primary text-white"> {{ heading.cnt }} </span>
                    {% endif %}

                    {% if heading.boat_num %}
                        <span class="badge badge-warning text-muted">
                            <a href="{% url 'boats:boat_detail' pk=heading.one_to_one_to_boat_id %}" class="text-muted">BOAT</a>
                        </span>
                    {% endif %}

                </div>

                {% if forloop.counter == 1 %}

                {% endif %}

            </div>


        {% endfor %}


    </div>

    <div class="col-2   text-right mr-3  item float-right" style=" position:absolute; top: 90px; right: 0px; ">
        <div class="btn-group-vertical btn-outline-dark rounded border border-success" role="group" aria-label="Button coalition"  >
            <a href="{% url "articles:add_article" pk=0 %}"><button type="button" class="btn btn-secondary rounded-0 border-bottom  ">Add an Article</button></a>
            <a href="{%  url "articles:add_heading" pk=0 %}"><button type="button" class="btn btn-secondary rounded-0 border-bottom " >Add new Heading</button></a>
            <a href="{%  url "articles:resurrection" %}"><button type="button" class="btn btn-secondary rounded-0">Recover  Articles</button></a>

        </div>
    </div>


{% endblock content%}

templates/articles/content.html
<!-- templates/articles/content.html  -->
{% extends "base.html" %}
{%  load bootstrap4 %}
{%  bootstrap_jquery "full" %}
{% load filtersandtags %}
{%  block title %}
    {{ object.title }} -{{ object.foreignkey_to_subheading.name }}
{% endblock title %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row mb-0  ">
            <div class="col-10">
                <h4 class="text-center alert alert-primary shadow-sm "> Upper-heading: {{ object.foreignkey_to_subheading.foreignkey }} ; Sub-heading: {{ object.foreignkey_to_subheading.name }}</h4>
                <h4 class="text-left font-italic   offset-1"> Article title:  {{ object.title }}</h4>
                <h4 class="text-left font-italic   offset-1"> Article content:  {{ object.content }}</h4>
            </div>


            <div class="col-2 text-right justify-content-end">
                {% buttons %}
                    <style>
                        .btn-group-vertical a, .btn-group-vertical button {
                            width: 100%;
                        }
                    </style>

                    <div class="btn-group-vertical text-right  rounded mr-3" role="group" aria-label="page management">


                    {% if request.GET.code == "boats"  and object.foreignkey_to_boat %}
                             <a href="{% url "boats:boat_detail" pk=object.foreignkey_to_boat_id %}"><button type="button" class="form-button btn secondary border-success" data-toggle="tooltip" data-placement="top" title="get back to the boat" > Back to the boat</button></a>


{% else %}
                        <a href="{% url "articles:show_by_heading"  pk=object.foreignkey_to_subheading_id%}{{ all }}"><button type="button" class="form-button btn secondary border-success" data-toggle="tooltip" data-placement="top" title="get back to the heading view" > Back to the heading</button></a>

{% endif %}


                        <a href="{% url "articles:comment" key="article" pk=object.pk %}"><button type="button" class="form-button btn secondary border-success  mt-2" data-toggle="tooltip" data-placement="top" title="Comment this article" > Comment</button></a>



                        {% if object.author == user %}
                            <a href="{% url "articles:article_edit" pk=object.pk %}"><button type="button" class="form-button btn secondary border-success mt-2
" data-toggle="tooltip" data-placement="top" title="Edit this article" > Edit the article</button></a>

                            <a href="{% url "articles:article_delete" pk=object.pk %}"><button type="button" class="form-button btn secondary border-success mt-2
" data-toggle="tooltip" data-placement="top" title="Delete this article" > Delete the article</button></a>
                            </div>

                        {% else %}
                            </div>

                            <div class="card mr-2 mt-2">
                                <div class="card-header">
                                    <strong class="text-muted">Edit the article</strong>
                                </div>
                                <div class="card-body">
                                    <h6 class="card-title">You aren't allowed to edit this article</h6>

                                    <p class="card-text">Only the author of the article <br> is allowed to edit or delete it </p>
                                </div>
                            </div>
                        {% endif %}
                {% endbuttons %}
        </div>



        <div class="row mt-2">
            <div class="col-auto offset-2 ">

                <table class="table  " style="font-size: 18px">
                    <tbody>
                    <tr class="table-active ">
                        <th scope="row"></th>
                        <td>Author</td>
                        <td>{{ object.author }}</td>
                    </tr>
                    <tr class="table-active   ">
                        <th scope="row"></th>
                        <td>Created at</td>
                        <td>{{object.created_at|date:"SHORT_DATE_FORMAT"   }}</td>
                    </tr>

                    {% if object.foreignkey_to_boat %}
                           <tr class="table-active   ">
                        <th scope="row"></th>
                        <td>Connected with the boat</td>
                        <td>{{object.foreignkey_to_boat.boat_name  }}</td>
                    </tr>
                    {% endif %}

                    <tr class=" table-active">
                        <th scope="row"></th>
                        <td>Read the article on a website</td>
                        <td><a href="{{ object.url_to_article }}">Url to the article on a web site</a></td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>


    </div>




    <div class="row">
        <div class="col">

{% for comment in comments %}


      <Ul style="list-style: none" class="mt-3 mr-3">
            <li> <strong>{{ comment.author }} </strong> <i> {{ comment.created_at|date:"SHORT_DATE_FORMAT"  }}

                {%  if request.user.username  == comment.author  %}

            <a href="{% url "articles:edit_comment" pk=comment.pk %}"><span class="badge badge-info">Edit comment</span></a>


                    {% elif  comment.pk|int_to_str  in allowed_comments  and not request.user.is_authenticated %}
<a href="{% url "articles:edit_comment" pk=comment.pk %}"><span class="badge badge-info">Edit comment</span></a>
                {% endif  %}

            </i></li>
            <li> {{ comment.content }} </li>

        </Ul>
        <hr>


            {% endfor %}

        </div>
    </div>


{% endblock content%}

templates/articles/resurrection.html
<!-- templates/articles/resurrection.html  -->
{%  extends "base.html" %}
{%  load bootstrap4 %}
{% block title %}
    restore the article
{% endblock %}

{% block content %}


    <div class="container-fluid">

        <div class="row ">
            <div class="col text-center">
                <h4 class="mt-3 font-italic mb-3"> List of the article made by <span class="font-weight-bold font">{{ request.user }}</span> available to recover </h4>
            </div>
        </div>

        <div class="row">
            <div class="col-10  offset-1">
                <form method="post" >
                    {% csrf_token %}
                    {% bootstrap_form form %}

                    <div class="row">
                        <div class="col text-center">
                            {% buttons %}
<div class="btn-group btn-group-lg" role="group" aria-label="Basic example">
                                <button type="submit"  name="submit"   class="form-button btn-lg btn-outline-success rounded-left font-weight-bold   btn btn-block " >Recover</button>
                                <a href="{% url "articles:articles_main" %}"> <button type="button"  name="back"   class="rounded-right form-button btn-lg btn-outline-primary  font-weight-bold   btn btn-block" style="width: 150%">Back </button> </a>
                                </div>

                            {% endbuttons %}
                        </div>
                    </div>

                </form>
            </div>
        </div>

    </div> <!--container-->

{% endblock content %}

templates/articles/show_by_subheading.html
<!--templates/articles/show_by_subheadings.html   -->
{% extends "base.html" %}
{%  load bootstrap4 %}

{% block title %}
    Articles are shown in their sub-headings
{% endblock title %}

{%  block searchform %}
{% endblock searchform %}


{% block content %}

    <div class="container-fluid-md mb-0">
        <div class="row mt-2">
            <div class="col ">&nbsp;</div>
            <form class="col-md-auto form-inline mr-3">
                {% bootstrap_form form show_label=False form_group_class="border border-success rounded"%}
                {%  bootstrap_button content="Search" button_type="submit" button_class="form-button btn secondary border-success" extra_classes='data-toggle="tooltip" data-placement="top" title="get back to the Articles main page"' %}
            </form>
        </div>
    </div>


    <div class="row mt-2 justify-content-start">
    <div class="col ml-3">
        {% if list_of_articles %}
            <ul class="list-unstyled">
             <h4 class="mb-3 "> {{ current_heading }}</h4>

                {% for article  in list_of_articles %}
                    <li class="    p-2  ">
                        {%  url "articles:detail"  current_heading_pk=current_heading.pk  pk=article.pk as url %}
                        <a href="{{ url }}{{ all }}"></a>
                        <div class=" ">
                           <h5> <a href="{{ url }}{{ all }}">
                                {{ article.title }}</a>

                           {% if article.foreignkey_to_boat %}
                                <span class="badge badge-warning text-muted ml-2">
                                    <a href="{% url "boats:boat_detail" article.foreignkey_to_boat_id %}" class="text-muted ">Connected to boat</a>
                                     </span>
                               {% endif %}

                           </h5>
                        </div>

                    </li>
                {% endfor %}
            </ul>

        {% endif %}
    </div>
    <div class="col text-right">

    {% buttons %}
        <a href="{% url "articles:articles_main" %}"><button type="button" class="form-button btn secondary border-success" data-toggle="tooltip" data-placement="top" title="get back to the Articles main page" style="margin-right: 16px"> Back to the Articles</button></a>


    <div class="row">
        <div class="col text-right mt-2">

                    <a href="{% url "articles:add_article"  pk=current_heading.pk  %}"><button type="button" class="form-button btn secondary border-success mt-0" data-toggle="tooltip" data-placement="top" title="Create new article" style="margin-right: 16px"> Create new article</button></a>
                {% endbuttons %}

            <div>

            </div>
        </div>
    </div>
    </div>
    </div>




{%  if page.has_other_pages %}
    <footer>
    <div class="  pagination pagination-centered justify-content-center mt-2  " >
{% bootstrap_pagination page url=keyword%}
    </div>
    </footer>
{% endif %}



{% endblock %}