api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
from rest_framework.authtoken import views as authtoken_views
from api import views


schema_view = get_schema_view(title="Pastebin Api")


router = DefaultRouter()

urlpatterns = [
    path('api-token-auth/', authtoken_views.obtain_auth_token, name="obtain-token"),
    path("schema/", schema_view, name="schema"),
    path("boats/<int:pk>/", views.BoatDetailView.as_view(), name="boatmodel-detail"),
    path("boats/", views.BoatsListView.as_view(), name="boatmodel-list"),
    path("users/login/", views.UserLoginView.as_view(), name="login"),
    path("users/registration/", views.UserRegistrationView.as_view(), name="user-registration"),
    path("users/profile/", views.UserProfileView.as_view(), name="user-profile"),
    path("users/<int:pk>/", views.ExtraUserDetailView.as_view(), name="extrauser-detail"),
    path("users", views.ExtraUserListView.as_view(), name="extrauser-list"),
    path("product/search/", views.ProductSearchListView.as_view(), name="product-search"),
    path("product/suggest/<str:word>/", views.SuggestionView.as_view(), name="product-suggest"),
    path("", views.api_root, name="api-root"),

]

articles/urls.py
from django.urls import path
from .views import *

app_name = 'articles'
urlpatterns = [
    path("<int:current_heading_pk>/<int:pk>/", ContentListView.as_view(), name="detail"),
    path("<int:pk>/", show_by_heading_view, name="show_by_heading"),
    path("comment/edit/<int:pk>/", EditCommentsView.as_view(), name="edit_comment"),
    path("comment/<str:key>/<int:pk>/", DoubleCommentView.as_view(), name="comment"),
    path("article_delete/<int:pk>/", ArticleDeleteView.as_view(), name="article_delete"),
    path("article_edit/<int:pk>/", ArticleEditView.as_view(), name="article_edit"),
    path("add_article/<int:pk>/", AddArticleView.as_view(), name="add_article"),
    path("add_heading/<int:pk>/", headingcreateview, name="add_heading"),
    path("resurrection/", ArticleResurrectionView.as_view(), name="resurrection"),
    path("", ArticlesMainView.as_view(), name="articles_main"),

]

boats/urls.py
from django.urls import path
from .views import *

app_name = 'boats'
urlpatterns = [

    path("accounts/reset/<uidb64>/<token>/", PassResConfView.as_view(), name='password_reset_confirm'),
    path("accounts/password_reset/", PassResView.as_view(), name="password_reset"),
    path("accounts/register/activate/<str:sign>/", user_activate_view, name="register_activate"),
    path('account/password/change', PasswordCorrectionView.as_view(), name="password_change"),
    path("account/profile/registerdone/", RegisterDoneView.as_view(), name="register_is_done"),
    path("accounts/profile/delete/", DeleteUserView.as_view(), name="profile_delete"),
    path("accounts/profile/change/", CorrectUserInfoView.as_view(), name="profile_change"),
    path("accounts/profile/add/", AddNewUserView.as_view(), name="add_new_user"),
    path("accounts/logout/", AdminLogoutView.as_view(), name="logout"),
    path("accounts/profile/", UserProfileView.as_view(), name='user_profile'),
    path("accounts/login/", AdminLoginView.as_view(), name="login"),
    path("boats/edit/<int:pk>/", viewname_edit, name="boat_edit"),
    path("boats/detail/<int:pk>/", boat_detail_view, name="boat_detail"),
    path("boats/delete/<int:pk>/", BoatDeleteView.as_view(), name="boat_delete"),
    path("boats/create/", viewname, name="boat_create"),
    path("boats/reversion/delete/<int:pk>/", ReversionDeleteView.as_view(),
         name="reversion_delete"),
    path("boats/reversion/confirmation/<int:pk>/", reversion_confirm_view,
         name="reversion_confirmation"),
    path("boats/reversion/", ReversionView.as_view(), name="reversion"),
    path("boats/render/pdf_to_file/<int:pk>/", render_pdf_view, name="pdf_to_file"),
    path("boats/render/pdf/<int:pk>/", Pdf.as_view(), name="pdf"),
    path("boats/rollback/<int:pk>/<int:version_id>/", RollbackView.as_view(), name="rollback"),
    path("boats/blocket/<int:pk>/<str:name>/", BlocketView.as_view(), name="blocket"),
    path("boats/", BoatListView.as_view(), name="boats"),
    path("feedback/", feedback_view, name="feedback"),
    path("map/<int:pk>/", map_show, name="map"),
    path("", IndexPageView.as_view(), name="index"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib. staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.views.defaults import permission_denied, page_not_found, server_error
from django.utils.functional import curry
from django.conf import settings
from django.conf.urls import url


urlpatterns = [
    path("social/", include('social_django.urls', namespace='social')),
    path("captcha/", include("captcha.urls")),
    path('admin/', admin.site.urls),
    path("articles/", include("articles.urls")),
    path("", include("boats.urls")),
    url(r'fancy-cache', include('fancy_cache.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path("api/", include("api.urls")),
]

# для отдачи статики в дебаг = фалс ---manage.py runserver --insecure
if settings.DEBUG:
    urlpatterns.append(path("static/<path:path>", never_cache(serve)))  # если не загр. картинки то смотреть сюда
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

# обработчик 403 ошибки(Access denied)
handler403 = curry(permission_denied, exception=Exception('Permission Denied'),
                   template_name='errors/403.html')
# обработчик 404 ошибки(Not Found)
handler404 = curry(page_not_found, exception=Exception('Page not Found'),
                   template_name='errors/404.html')

# названия для админки
admin.site.site_header = "Boat's project  Admin"
admin.site.site_title = "BOATS Admin Portal"
admin.site.index_title = "BOATS administration page"

boats/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .utilities import files_list, get_timestamp_path, clean_cache, clean_map
from django.core.exceptions import ObjectDoesNotExist, EmptyResultSet
from django.core import validators
from django_countries.fields import CountryField
from easy_thumbnails.files import get_thumbnailer
from django.db.models.fields import Field
from .lookups import NotEqual
from django.conf import settings
import os
import sys
from datetime import datetime
from django.contrib.postgres.indexes import BrinIndex
from django_boto.s3.storage import S3Storage
from django.shortcuts import reverse
from fancy_cache.memory import find_urls


#   регистрация кастомного lookup
Field.register_lookup(NotEqual)


""" вторичная модель изображений"""


class BoatImage(models.Model):

    boat_photo = models.ImageField(upload_to=get_timestamp_path, blank=True, null=True,
                                   verbose_name='Boat photo', )
    boat = models.ForeignKey("BoatModel",  on_delete=models.SET_NULL, verbose_name="Boat "
                                                                    "ForeignKey", null=True)
    memory = models.PositiveSmallIntegerField(blank=True, null=True)
    change_date = models.DateTimeField(db_index=True, editable=False, auto_now=True)

    class Meta:
        verbose_name = "Boat photo"
        verbose_name_plural = "Boat photos"
        order_with_respect_to = "boat"  # new

    #  запоминаем значение ФК на случай  срабатывания on_delete = SET_NULL (для последующего
    #  восстановления)
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        # удаляем изображения без привязки к лодкам со сроком последнего доступа к файлам более 2
        # месяцев
        useless_old_images = BoatImage.objects.filter(boat_id__isnull=True,
                                                      memory__isnull=False)
        for image in useless_old_images:
            try:
                if datetime.now().timestamp() - os.path.getmtime(image.boat_photo.path) > \
                        5184000:
                    image.true_delete(self)  # удаляем по настоящему
            except NotImplementedError:  # на случай работы сайта на Heroku
                if (datetime.now() - image.change_date).seconds > 5184000:
                    image.true_delete(self)

        if self.boat_id and not self.memory:  # сохраняем
            self.memory = self.boat_id
        elif not self.boat_id and self.memory:  # восстанавливаем
            self.boat_id = self.memory
        elif self.boat_id and self.memory and self.boat_id != self.memory:  # корректируем на
            # крайняк
            self.memory = self.boat_id
        models.Model.save(self, force_insert=False, force_update=False, using=None,
                          update_fields=None)

    def true_save(self, force_insert=False, force_update=False, using=None,
                  update_fields=None):
        """сохраняем по настоящему"""
        return models.Model.save(self, force_insert=False, force_update=False, using=None,
                          update_fields=None)

    def delete(self, using=None, keep_parents=False):  # удаляем thumbnails ассоциированные
        thumbnailer = get_thumbnailer(self.boat_photo)
        thumbnailer.delete_thumbnails()
        # вместо удаления фоток мы устанавкливаем их ФК в <null>
        self.boat.boatimage_set.remove(self)
        #  Устанавливаем время последнего доступа и последнего изменения файла на текущее время
        try:
            os.utime(self.boat_photo.path, (datetime.now().timestamp(),
                                datetime.now().timestamp()))
        except NotImplementedError:  # на случай работы сайта на Heroku
            pass
        models.Model.save(self, update_fields=["change_date", ])  # для обновления даты
        # последнего изменения.
        # Нужно для реализации метода очистки  удаленных фоток через Х дней на Хероку

    def true_delete(self, using=None, keep_parents=False):
        """ Удаляем по настоящему"""
        return models.Model.delete(self, using=None, keep_parents=False)

    def __str__(self):
        try:
            return "Boat photo - %s, boat name - %s, boat id - %s, photo id - %d " % \
               (self.boat_photo.name, self.boat.boat_name, self.boat_id, self.pk)
        except AttributeError:
            return "No image"

    def filename(self):
        """метод возвращает имя файла"""
        return os.path.basename(self.boat_photo.name)

    @staticmethod
    def clean_media_root():  # Не использовать в тестах!!!! Даже и не думай!!!
        """метод очистки лишних изображений в медиа рут"""
        if 'test' in sys.argv or 'test_coverage' in sys.argv:
            print("Do not use this method in tests. It is dangerous for your db!!!")
        else:
            files_in_db = {image.filename() for image in BoatImage.objects.all().only(
                "boat_photo")}
            useless_files = files_list() - files_in_db
            counter = 0
            for file in useless_files:
                os.remove(os.path.join(settings.MEDIA_ROOT, file))
                counter += 1
            print(counter, "\xa0\\files were removed from MEDIA_ROOT")


""" Первичная модель информации о лодке"""


class BoatQuerySet(models.QuerySet):  # стр 331
    """Упорядочевывает записи по кол-ву коментов"""
    def order_by_comment_count_desc(self):
        return self.annotate(cnt=models.Count("comment")).order_by("-cnt")

    def order_by_comment_count_asc(self):
        return self.annotate(cnt=models.Count("comment")).order_by("cnt")


class BoatModel(models.Model):

    objects = BoatQuerySet.as_manager()

    SLOOP = "SL"
    KETCH = "KE"
    YAWL = "YA"
    CAT_KETCH = "CK"
    CUTTER = "CU"

    CHOICES = (
        (None, "Please choose  the rigging type"),
        (SLOOP, "Sloop"),
        (KETCH, "Ketch"),
        (YAWL, "Yawl"),
        (CAT_KETCH, "Cat Ketch"),
        (CUTTER, "Cutter")
    )

    author = models.ForeignKey("ExtraUser", on_delete=models.DO_NOTHING,
                               verbose_name="Author of the entry")

    boat_name = models.CharField(max_length=20, unique=True, db_index=True,
                                 verbose_name="Boat model",
                                 help_text="Please input boat model")

    boat_length = models.FloatField(null=False, blank=False, verbose_name="Boat water-line "
                                "length", help_text="Please input boat water-line length",)

    boat_description = models.TextField(blank=True, verbose_name="Boat description",
                                        help_text="Please describe the boat", )

    boat_mast_type = models.CharField(max_length=10, choices=CHOICES,
                                      verbose_name="Boat rigging type",
                                      help_text="Please input boat rigging type")

    boat_price = models.PositiveIntegerField(verbose_name="price of the boat",
                                                  help_text="Please input boat price", )

    boat_country_of_origin = CountryField(verbose_name="Boat country of origin",
                                          blank_label="Select country of origin",
                                          help_text="Please specify boat's country of origin")

    boat_sailboatdata_link = models.URLField(max_length=100, blank=True,
                                             verbose_name="URL to Sailboatdata",
                                             help_text="Please type in URL to Sailboatdata "
                                                       "page for this boat")

    boat_keel_type = models.CharField(max_length=50, verbose_name="Boat keel type",
                                      help_text="Please specify boat's keel type")

    boat_publish_date = models.DateTimeField(auto_now_add=True)

    boat_primary_photo = models.ImageField(upload_to=get_timestamp_path, blank=True, #"photos/"
                                           verbose_name='Boat primary photo',
                                           help_text="Please attach a primary photo of the "
                                                     "boat")
    first_year = models.PositiveSmallIntegerField(blank=True, null=True,
                                    verbose_name="first manufacturing year of the model")
    last_year = models.PositiveSmallIntegerField(blank=True, null=True,
                                    verbose_name="Last manufacturing year of the model")
    change_date = models.DateTimeField(db_index=True, editable=False, auto_now=True)

    class Meta:
        verbose_name = "Boats primary data"
        verbose_name_plural = "Boats primary data"
        ordering = ["-boat_publish_date"]
        indexes = (BrinIndex(fields=["boat_publish_date"]),)
        constraints = [
        models.CheckConstraint(check=models.Q(first_year__gte=1950), name='first_year__gte=1950'),
        ]

    def __str__(self):
        return self.boat_name

    def delete(self, using=None, keep_parents=False):
        import articles.models  # to avoid circular import with articles
        """
            # очистка всех пустых подкатегорий  в категории "Articles on boats" без статей и без 
            связи с
            # лодкой
            # - условия срабатывания системы очистки:
            # 1 находится в папке Articles on boats
            # 2 нет связи с лодкой
            # 3 нет связанных не удаленных статей 
        """

        try:
            subheadings_query_set = articles.models.SubHeading.objects.filter(
                foreignkey_id=articles.models.UpperHeading.objects.get(
                            name__exact="Articles on boats").pk,
                one_to_one_to_boat_id__isnull=True)
            for subheading in subheadings_query_set:
                if not subheading.article_set(manager='reverse').exists():

templates/boat_detail.html
<!-- templates/boat_detail.html  -->
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{%  load thumbnail %}
{% load i18n %}
{% bootstrap_jquery "full" %}
{% load filtersandtags %}
{% load cache %}

{% block title %}
    {{ current_boat.boat_name }}
{% endblock title %}

{% block content %}



    {% cache "60*60*24"|multiplier boat_detail_boat   EQ.eq_current_boat  request.user.is_authenticated %}

    <div class="container-fluid">
        <div class="row mt-3">
            <div class = "col-md-3 text-left">

                <ul type="square" class="border-right">
                    <h4 > {% trans "Boat details" %}</h4>
                    <li>Boat name -<strong>{{ current_boat.boat_name }}</strong></li>
                    <li> Entry Author-{{ current_boat.author}}</li>

                    <li>Boat waterline length-{{ current_boat.boat_length }} feats </li>
                    <li>Boat rigging type-{{ current_boat.get_boat_mast_type_display }}</li>
                    <li >Country of origin-{{ current_boat.boat_country_of_origin.name }}
                        <img class=" align-self-center " style="margin: 6px 4px 0; width: 35px; height: 20px; align-content: center" src='{{current_boat.boat_country_of_origin.flag}}'/> </li>

                    <li>Boat keel type -{{ current_boat.boat_keel_type }}</li>
                    <li>Publishing date-
                        {{ current_boat.boat_publish_date|date:"SHORT_DATE_FORMAT"  }}</li>
                    <li>Price-{{ current_boat.boat_price }} &euro;</li>
                    <li>Manufacturing history of the model - {{ current_boat.first_year }} to {{ current_boat.last_year }}</li>

                    <li> <a href="{{ current_boat.boat_sailboatdata_link }}" target="_blank">Link to SailboatData</a></li>

                    <li><a href="https://www.blocket.se/hela_sverige?q={{ current_boat.boat_name }}&cg=1060&w=3&st=s&ps=&pe=&c=1062&ca=11&is=1&l=0&md=li" target="_blank">Check it on www.blocket.se</a></li>

                    <li><a href="{% url "boats:blocket" pk=current_boat.id name=current_boat.boat_name|slugify  %}" target="_blank">Open list of BLOCKET announcements on a separate page</a></li>

                 <li><a href="
https://www.yachtworld.com/core/listing/cache/searchResults.jsp?man={{ current_boat.boat_name }}&is=&type=&luom=126&fromLength=&toLength=&fromYear=&toYear=&pricderange=Select+Price+Range&Ntt=&fromPrice=0&toPrice=&searchtype=homepage&cit=true&slim=quick&ybw=&sm=3&Ntk=boatsEN&currencyid=100
" target="_blank">Find {{ current_boat.boat_name|upper }} on Yachtworld</a></li>

                </ul>
            </div> <!--col-->




            <div class="col-md-7 border-right ">
                <p><span class="font-weight-bold"> Description -&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>{{ current_boat.boat_description }}</p>


                <div class="btn-group dropright border   ">
  <button type="button" class="btn btn-secondary dropdown-toggle border-success rounded" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Get this as PDF
  </button>
  <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
    <a class="dropdown-item" href="{%  url "boats:pdf" pk=current_boat.pk %}"target="_blank">Open as a  PDF</a>
    <a class="dropdown-item" href="{%  url "boats:pdf_to_file" pk=current_boat.pk %}">Download PDF to your computer</a>
  </div>
</div>
            </div><!--col-->





            <div class="col-md-2  justify-content-end text-right mr-0  ">

                <style>
                    .btn-group-vertical a, .btn-group-vertical button {
                        width: 100%; margin-right: 0px;
                    }
                </style>

                <div class="btn-group-vertical btn-outline-dark rounded border border-success mr-2" role="group" aria-label="page management"  >
                    <a href="{% url "boats:boats"   %}"><button type="button" class="btn btn-secondary rounded-0 border-bottom">Back</button></a>
                    <a href="{% url "boats:boat_edit" current_boat.pk %}"> <button type="button" class="btn btn-secondary rounded-0 border-bottom ">Edit</button></a>
                    <a href="{% url "boats:boat_delete" current_boat.pk %}"><button type="button" class="btn btn-secondary rounded-0 border-bottom">Delete</button></a>
                    <a href="{%  url "articles:comment" key="boats" pk=current_boat.pk %}"><button type="button" class="btn btn-secondary rounded-0 ">Comment</button></a>
                </div>

{% endcache %}


{% cache "60*60*24"|multiplier boat_detail_versions   EQ.eq_versions  request.user.is_authenticated %}


{% if request.user == current_boat.author %}
 <div class="row text-right mt-2">
 <div class="col">
     <form action="{{ request.get_full_path_info }}" method="post" name="form1" id="1">
{% csrf_token %}

                    <select class="custom-select" name="rollback">
                        <option selected value="" class=" ">Select rollback date </option>
                        {% for version in versions %}
                        <option value="{{ version.id }}">--{{ version.revision.date_created }}</option>
                          {% endfor %}
                    </select>
     {% buttons %}
         <button type="submit" class="btn btn-secondary   border-success mt-2 rounded mr-1" style="width:106px">Rollback</button>
     {% endbuttons %}

   </form>
 </div>
</div>
{% endif %}

{% endcache %}


{% cache "60*60*24"|multiplier boat_detail_articles   EQ.eq_articles  current_boat.boat_name %}

                <div class = row >
                    <div class="col mr-1">

                            {% if articles|length < 5 %}
                            {%  for article in articles %}
                                {% if forloop.first %}<h6 class="mt-4"> Articles on {{ current_boat.boat_name }}</h6>{% endif %}
                                <ul type="square" class="border-right mt-2 text-right " style="list-style: none" >
                                    <li><a href="{% url "articles:detail" current_heading_pk=article.foreignkey_to_subheading_id  pk=article.pk %}{{ all }}">{{ article.title }}</a></li>
                                </ul>
                                {% empty %}
                                <h6 class="mt-4"> <span style="font-size: 22">{{ current_boat.boat_name }}</span> doesn't have any article. </h6>
                            {% endfor %}

                                {% else %}

                                  <h6 class="mt-4"> Articles on {{ current_boat.boat_name }}</h6>

                                 <div class="btn-group dropleft">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width:116px">
    Articles
  </button>
  <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
    {%  for article in articles %}

                                <ul type="square" class="border-right mt-2 " style="list-style: none" >
                                    <li><a href="{% url "articles:detail" current_heading_pk=article.foreignkey_to_subheading_id  pk=article.pk %}{{ all }}">{{ article.title }}</a></li>
                                </ul>

                            {% endfor %}
  </div>
</div>

{% endif %}
                    </div>
                </div>




                        <a href="{%  url "articles:add_article" current_boat.heading.pk    %}"><button type="button" class="btn btn-secondary   border-success mt-2 rounded  " style="width:120px">Add an article</button></a>

                    </div>
                </div>


            </div>
        </div>
    </div>



{% endcache %}


{% cache "60*60*24"|multiplier boat_detail_images   EQ.eq_images   request.user.is_authenticated %}

<div class="row mx-3  mt-3">
    {% for instance in images %}

        <a  href=" {{ instance.boat_photo.url}}"> <img class="  ml-3 mb-2" src="{% thumbnail instance.boat_photo "default"  %}"></a>


    {% endfor %}
</div>

{% endcache %}



{% cache "60*60*24"|multiplier boat_detail_comments  EQ.eq_comments  request.user.is_authenticated %}

    {% for comment in comments %}


      <Ul style="list-style: none" class="mt-3 mr-3">
            <li> <strong>{{ comment.author }} </strong> <i> {{ comment.created_at|date:"SHORT_DATE_FORMAT"  }}



                {%  if request.user.username  == comment.author  %}

            <a href="{% url "articles:edit_comment" pk=comment.pk %}"><span class="badge badge-info">Edit comment</span></a>


                    {% elif  comment.pk|int_to_str  in allowed_comments  and not request.user.is_authenticated %}
<a href="{% url "articles:edit_comment" pk=comment.pk %}"><span class="badge badge-info">Edit comment</span></a>
                {% endif  %}

            </i></li>
            <li> {{ comment.content }} </li>

        </Ul>
        <hr>


            {% endfor %}

{% endcache %}







{% endblock content %}

templates/index.html
<!-- templates/index.html -->
{%  extends "base.html" %}
{%  load bootstrap4 %}
{% bootstrap_jquery "full" %}
{%  load static %}
{% load cache %}
{% load filtersandtags %}



{% block content %}
    {% cache "60*60*24*7"|multiplier index  %}
    <style>
        #bg{
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
            background-attachment: fixed;
        }
    </style>
    <body id="bg" style="background-image: url('{% static "boats/imgonline-com-ua-Resize-0iLiZkzwokfsv78.jpg"%}')";>








        <div class="row" >
<div class="col" style="position: fixed; bottom: 0; left: 0;z-index: 500; margin-bottom: 27px;   ">

    <script>
$(function(){
  $('[data-toggle="tooltip"]').tooltip();
});
 </script>

                        <a href="{%  url "boats:feedback" %}" class="btn btn-primary btn-lg font-weight-bold text-dark  rounded " style=" background-color: rgba(169,139,68,0.75); border: rgba(247,79,107,0.64) 4px solid"   data-toggle="tooltip" data-placement="top" title="Send message to me , if you like"  >Feedback</a>

</div>

                    </div>




{% endcache %}
{% endblock content %}

templates/reversion.html
<!--templates/reversion.html   -->
{%  extends "base.html" %}
{% load bootstrap4 %}
{% load thumbnail %}
{%  load static %}
{% bootstrap_jquery "full" %}
{% load cache %}
{% load filtersandtags %}

{% block title %}
    Reversions
{% endblock %}
{% block content %}
{% cache "60*60*24"|multiplier reversion id_eq %}


    <style>
        body {
            background-image: url({% static "boats/SCS-logo3-e1463360121342.jpg" %});
            background-repeat: no-repeat, repeat;
            background-position: center, center;
            background-size: 60%;
            background-attachment: fixed;
        }
    </style>

    <script>
        $(function(){
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>




    <div class="offset-10">
        <img    class="  " style="position: absolute;   " height=  width= src="{% static "boats/images (2).jpg" %}" alt="save the mf boat">
    </div>

    <div class="container"   >


        <div class="text-center my-4 ">
            <h3 class="font-weight-bold text-monospace" > List of the boats created by {{ request.user.username }} available for recovery </h3>

        </div>



        <Ul >

            {% for instance in versions|dictsort:"object_repr" %}
                <div class="row">
                    <div class="col-2 offset-4 ">
                        <li><h6 class="text-center mb-3  " style="font-size: 20">{{ instance.object_repr }}</h6></li>
                    </div>
                </div>



                <div class="row offset-2">
                    {% for image in images %}


                        {% ifequal instance.object_id  image.memory     %}



                            <a  href=" {{ image.boat_photo.url}}"> <img class=" border border-secondary rounded ml-3 mb-2" src="{% thumbnail image.boat_photo "medium"  %}">    </a>



                        {% endifequal %}

                    {% endfor %}

                    {%  if instance.object_id  not in images.memory_list  %}
                        <img class="   ml-3 mb-2 border border-secondary rounded"  height=135 width=135 src="{% static "boats/sailing-boat-yacht-logo-vector-17317504.jpg" %}" alt="boat image" data-toggle="tooltip" data-placement="right" title="This boat doesn't have any photo">
                    {%  endif %}
                    <div class="col float-left">
                        <a href="{% url "boats:reversion_confirmation" pk=instance.object_id %}" class="badge badge-success">Recover</a><br>
                        <a href="{% url "boats:reversion_delete" pk=instance.object_id %}" class="badge badge-danger mt-2">Delete Reversion</a>
                    </div>


                </div>
            {% empty %}
                <h5 class="text-center  text-warning " style="font-size: 20">You dont have any deleted boats yet</h5>
            {% endfor %}
        </Ul >




    </div> <!--container


{% endcache %}
{% endblock content %}